#!/bin/bash
sudo yum install git -y
#git clone https://github.com/MRowshan/go-linux-install && ./go-linux-install/go-install
#cd
#export PATH=$PATH:/usr/local/go/bin

sudo useradd go-user
sudo su - go-user
mkdir .ssh && chmod 700 .ssh && cd .ssh
touch authorized_keys && chmod 600 authorized_keys

echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDQIe9B8FtsQe0uN/obt6HSxrOkLMqGujep29w0+vhsTQV0z9YGIR5MF8XLRXHPBJjHnYuyF+uR4/qomnYi4Frc3p2ZfAK+UjLCC4a322GONOVBQwHLhDqpDgmIPKHzw4Dxk/Ib5rkcFTWRkDEO1438KLOhJmH+joCPxo2Z+I0YyEwfmBe4lKRXrnpjZo3AqCvUVPXx2WADMnv97Y3Yak4fY63YKiZR0y8LGOJyNMVV4tPWOTs0TTGiv+N34ZT7lE734sZe2OAiWvTtk0wz+c/DWgu99KEHYcKFXgu4aB38boWFdCT1519TXvaI2KC5H0toRs6dAw1icNFhdXWD45cB Admin@STUDENT05" >> authorized_keys

cd
git clone https://github.com/MRowshan/vim && ./vim/install
#git clone https://github.com/MRowshan/go-http-server
gsutil cp -r gs://centos7-startup ~
export PATH=$PATH:/usr/local/go/bin

cd /home/go-user/centos7-startup/app-executable
chmod +x app
