#!/bin/bash
sudo yum install git -y

sudo useradd go-user
sudo su - go-user
mkdir .ssh && chmod 700 .ssh && cd .ssh
touch authorized_keys && chmod 600 authorized_keys

echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDQIe9B8FtsQe0uN/obt6HSxrOkLMqGujep29w0+vhsTQV0z9YGIR5MF8XLRXHPBJjHnYuyF+uR4/q
omnYi4Frc3p2ZfAK+UjLCC4a322GONOVBQwHLhDqpDgmIPKHzw4Dxk/Ib5rkcFTWRkDEO1438KLOhJmH+joCPxo2Z+I0YyEwfmBe4lKRXrnpjZo3AqC
vUVPXx2WADMnv97Y3Yak4fY63YKiZR0y8LGOJyNMVV4tPWOTs0TTGiv+N34ZT7lE734sZe2OAiWvTtk0wz+c/DWgu99KEHYcKFXgu4aB38boWFdCT15
19TXvaI2KC5H0toRs6dAw1icNFhdXWD45cB Admin@STUDENT05" >> authorized_keys

cd
git clone https://github.com/MRowshan/vim && ./vim/install
git clone https://github.com/MRowshan/go-http-server
